### PR TITLE
Read-only View

### LINKED ISSUE #377: Make Board Read Only
# Feature Request

**As a** peoplemover user
**I would** like to access a read-only view of PeopleMover
**so that** I don't accidentally make any changes that I am not authorized to make

## Acceptance Criteria

**Given** I receive a link that grants me me read only access
**When** I click it
**Then** I can see PeopleMover
**And** I can only sort, filter, click account dropdown (with limited options - only "Sign Out")
**And** access my dashboard by clicking the PeopleMover logo

## Notes

Please provide notes on this feature if applicable.

### PR DESCRIPTION
**Pull request by alexwojtala**
## Issue
Resolves #377 

## What was done
- [x] Disallow access to any post, put or delete endpoint in read only view
- [x] Disallow access to get endpoints in read only view that have a requested date other than today
- [x] Disable UI for editing a space in read only view

## How to test
1. Go to a space not in your space dashboard
2. Make sure you cannot edit that space in anyway
3. Make sure you cannot view data for dates other than today

### FOR DEVS
Feature URL: See feature branch

### FOR APPROVAL
Approval URL: See Approval branch

### CODE REVIEW

**Review by michaelrygiel — DISMISSED** [review]

**Review by smle225 — CHANGES_REQUESTED** [review]
- Overall disable button color: HEX #BFBCBB or RGB 191,188,187,1
- seletionTabButton disable color: HEX #BFBCBB or RGB 191,188,187,1
- addPerson button background color: #BFBCBB or RGB 191,188,187,1
- newProduct button is slightly lighter than the productCardContainer. 
- Add a block/stop icon when you hover over edit icons to make it consistent with rest of the disabled interaction

**Comment by smle225** [comment]
Also @willot mentioned about view only icon on the sub header. So I'm just documenting that we need to add little CSS code for this :)
Screen Shot 2020-11-30 at 3 07 08 PM

**Comment by smle225** [comment]
Note hover is hoverable. We need to remove that functionality

**Review by smle225 — APPROVED** [review]

**Review by willot — APPROVED** [review]
It is working!!! Get this thing out!!

**Pull request merged**
