### PR TITLE
Swap out font awesome icons for Material Design Icons

### LINKED ISSUE #461: Icon package
**As a** FLIP Engineer
**I would** like a more efficient way of handling icons
**so that** I can access icons faster and save time when working on icon-related stories

**Given** I am on a icon related story  
**When** I need an icon 
**Then** I grab the CSS code from this package myself

Icon package: https://material.io/resources/icons/?style=baseline
Github guide: http://google.github.io/material-design-icons/

Design:
Calendar view: https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=5519%3A3

Edit/Trash
https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=5447%3A163

Icon Replacement

### PR DESCRIPTION
**Pull request by michaelrygiel**
## Issue
Resolves #461

## What was done
- [x] Replace almost all icons in PeopleMover with icons from the Material Designs plugin

## How to test
1. Check all icons on space dashboard
2. Check all icons on a space
3. Check all icons on modals (My Tags, My Roles, Product, Person, etc)

Icons URL: https://material.io/resources/icons/?style=baseline

### FOR DEVS
Feature URL: https://featurebranchui.apps.pd01i.edc1.cf.ford.com/

Feature Branch Deployment: https://jenkins-fordlabs.apps.pd01e.edc1.cf.ford.com/job/PeopleMover/job/Deploy%20PeopleMover%20FeatureBranch/

### FOR APPROVAL
Approval URL: https://approvalbranchui.apps.pd01i.edc1.cf.ford.com/

Approval Branch Deployment: https://jenkins-fordlabs.apps.pd01e.edc1.cf.ford.com/job/PeopleMover/job/Deploy%20PeopleMover%20ApprovalBranch/

### CODE REVIEW

**Review by willot — CHANGES_REQUESTED** [review]
We should host the library or see if we can get it from Ford Nexus. In case people cannot get it through VPN

**Review by smle225 — CHANGES_REQUESTED** [review]
- Add padding for productNameEditContainer: 6px 5px 6px 9px - so that the product name is more aligned
- productControlsContainer need to be more vertically aligned with the productName - but I don't know how...
- Adjust the height of calendarCustomInput: 208.062 x 25 - so that it's vertically centered

But 👍 👍 👍 👍 👍

**Comment by willot** [comment]
the arrows on the side are much closer to the border on firefox than chrome
Screen Shot 2020-11-12 at 3 59 44 PM

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

There are more padding around the + sign on the left and the right (chrome, didn't check firefox)
Screen Shot 2020-11-12 at 3 56 52 PM

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

The plus sign is not as bold than used to be
Screen Shot 2020-11-12 at 3 53 27 PM

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

The closing x is not as bold than it used to be
Screen Shot 2020-11-12 at 3 52 18 PM
Same as above
Screen Shot 2020-11-12 at 3 51 50 PM

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

The file icone when there is a note in a person is weird
Screen Shot 2020-11-12 at 3 50 56 PM

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

The space between the pencil and the trash is bigger than it used to be
Screen Shot 2020-11-12 at 3 49 44 PM

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

The arrow is not vertically center with the date anymore
Screen Shot 2020-11-12 at 4 17 02 PM

**Review by smle225 — APPROVED** [review]

**Review by willot — APPROVED** [review]
#Lot of stuff look weird but we will address that on a new story

**Pull request merged**
