### PR TITLE
Reassigned drawer

### PR DESCRIPTION
**Pull request by alexwojtala**

### CODE REVIEW

**Comment by alexwojtala** [comment]
Here is where you can check it out: https://pr-147ui.apps.pd01i.edc1.cf.ford.com/

Lets us know what you find!

**Comment by jshaddac** [comment]
SO GOOD!
@alexwojtala You don't currently have the persons role in window. Is that a seperate story or should that be aded before accepting this one?

**Comment by alexwojtala** [comment]
@jshaddac That can be done in this story, for now we just pulled the code from the old ui, which did seem to get most of the current design. We figured we would just get it up quickly for feedback, we can definitely add that!

**Comment by alexwojtala** [comment]
After taking another look, you should be able to see the person's role, right under their name

**Comment by jshaddac** [comment]
Took me a second to realize that the person I was moving around didnt even have a role. Looks good!!!

**Pull request merged**
